### ISSUE TITLE
hostname ipaddress nil

### ISSUE THREAD

**Issue by jessehub** [chef-cookbooks/chef_hostname#22]
### Cookbook version

0.4.0 - 0.4.2 (haven't tested prior version)
### Chef-client version

chef-solo 12.15.19
### Platform Details

kitchen-vagrant ubuntu-14.04, centos-7.2
### Scenario:

Using ipaddress resource property with a nil value
### Steps to Reproduce:

```
hostname "stringy.dingy.do" do
     ipaddress nil
end
```
### Expected Result:

/etc/hosts would not be updated
### Actual Result:

Deprecated features used!
         An attempt was made to change ipaddress from "10.0.2.15" to nil by calling ipaddress(nil). In Chef 12, this does a get rather than a set. In Chef 13, this will change to set the value to nil. at 1 location: .... (my call of the hostname resource block)

**Comment by lamont-granquist** [comment]
that might be a bug in core chef

**Comment by lajoie** [comment]
I'm experiencing the same thing.

Regardless of whether it's really a bug in Chef, it appears from the warning message that Chef intends to do *something* with this property/method from now on.  As such, would you consider a different name for this property within the hostname resource?  Maybe 'ip_address'?

**Comment by lamont-granquist** [comment]
This looks like its just using a feature of Chef 13 (nillable properties) that wasn't supported in Chef 12, as Chef 12 is going to go EOL soon this isn't going to get fixed.  Upgrading to 13 (or 14 soon) will fix it.
