### ISSUE TITLE
cloud-init resets hostname

### ISSUE THREAD

**Issue by jessehub** [chef-cookbooks/chef_hostname#23]
### Cookbook version
0.4.2

### Chef-client version
n/a

### Platform Details
AWS, and other cloud images that use cloud-init

### Scenario:
Hostname set via cookbook should persist across reboots in EC2 with newer Redhat releases

### Steps to Reproduce:
Standard Centos7 and Fedora20 EC2 images, after setting hostname and rebooting will revert to dhcp provided hostname.

### Expected Result:
Expecting hostnamectl results to be persistent, and respect user provided configuration after rebooting.

### Actual Result:
/etc/hostname and other critical files are reset to the initial hostname of the machine on boot

**Comment by jessehub** [comment]
I have a PR for this, but needs to go through testing.

**Comment by jessehub** [comment]
Can use the https://supermarket.chef.io/cookbooks/cloud_init cookbook to deal with this

**Comment by lamont-granquist** [comment]
that seems like a good way to deal with this issue.
