### ISSUE TITLE
cookbook not cookstyle compliant

### ISSUE THREAD

**Issue by bottkv488** [chef-cookbooks/chef_hostname#34]
I don't mean to be indoctrinating, but as this is a cookbook *made by chef* we should stick to common best practises? ;)
I'm willing to volunteer (first PR is already on the way) if we all agree on cookstyle rules.

### Cookbook version
0.6.x

### chefdk version
2.0.26

### Platform Details
Mac OS Sierra

### Steps to Reproduce:
`$ cookstyle`

### Expected Result:
cookstyle should not show violations

**Comment by lamont-granquist** [comment]
no, its meant to go into core chef as soon as i can get around to it.  it should be chefstyle compliant, not cookstyle.
