### ISSUE TITLE
Use TAB instead of whitespace after IP

### ISSUE THREAD

**Issue by dgarstang** [chef-cookbooks/chef_hostname#40]
when the hostname resources writes the hostname to the /etc/hosts file, it does so with a whitespace between the IP address and the name. This should probably be a tab. We use the hostsfile recipe later in our run list, and it rewrites this line because it wants to use a tab. The result is that the file is updated on every single chef run.

**Comment by lamont-granquist** [comment]
There's no standard as to what whitespace to use in /etc/hosts.  The hostsfile recipe should really be updated to be insensitive to matching different kinds of whitespace.
